### ISSUE TITLE
Offline access for feature alignment with other language SDKs

### ISSUE THREAD

**Issue by billxinli** [configcat/node-sdk#37]
### Is your feature request related to a problem? Please describe.

Can we get the JS (frontend, SSR, Node) SDKs to be feature aligned with other language SDKs?

Specifically offline and local configurations of flags for the purpose of local development or testing?

### Describe the solution you'd like

For the javascript constructors to take an optional "local" configuration.

### Additional context

Add any other context about the feature request here.

For example with PHP SDK it allows for: https://configcat.com/docs/sdk-reference/php/#flag-overrides

**Comment by laliconfigcat** [comment]
Hello @billxinli ,

Thanks for reaching out. We are working on this feature in all of our SDKs. I don't have an exact ETA for this. We'll keep you updated.

Cheers,
Lali

**Comment by laliconfigcat** [comment]
Hello,

The https://github.com/configcat/common-js/pull/45 PR will include this feature.

Cheers,

**Comment by laliconfigcat** [comment]
Hello @billxinli ,

We just released a new version of all of our JS-based SDKs with the new features. I hope you'll like it. The documentation is not ready yet, but I hope the interface is self-describing enough to get started with it.

Cheers,
Lali
