### ISSUE TITLE
'got' dependency is out of date

### ISSUE THREAD

**Issue by jdstrand** [configcat/node-sdk#45]
Hi!

The `got` dependency is out of date. https://github.com/configcat/node-sdk/blob/master/package-lock.json#L13 is specifying `9.6.0` but https://github.com/advisories/GHSA-pfrx-2q88-qq97 lists the fix is in `11.8.5` or `12.1.0`.

Thanks!

**Comment by endret** [comment]
Hi @jdstrand ,

Thank you for the report, we are starting the investigation.

Regards,
Endre

**Comment by z4kn4fein** [comment]
Hello @jdstrand,

We released the version `8.0.0` from where we removed the dependency to `got`, so upgrading to it must solve the linked security issue.

Thanks!

**Comment by jdstrand** [comment]
> Hello @jdstrand,
> 
> We released the version `8.0.0` from where we removed the dependency to `got`, so upgrading to it must solve the linked security issue.

Thanks for working on this! :)
