### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ziofat** [configcat/node-sdk#7]
Hi, my service are running behind a firewall which require a proxy to access configure file. Node SDK seems not able to send request over proxy.

**Comment by mr-sige** [comment]
Hi there,
Adding proxy support to our SDKs is on our roadmap for this year.
We have already implemented in the .NET SDK:
Repo: https://github.com/configcat/.net-sdk
Related docs: https://configcat.com/docs/sdk-reference/csharp/#using-configcat-behind-a-proxy

Also we welcome contributions and happy to help and provide all the necessary info to do that.

**Comment by ziofat** [comment]
That will be hard to implement proxy support with `ky` as http client. The `ky`'s author has another package called `got` for nodejs which has proxy support.
Is that OK for you to replace `ky` with another http client?

**Comment by mr-sige** [comment]
I don't see a reason why not. I have added `ky` to support SSR (server side rendering) applications and node.js on the same time. If `got` fulfills this as well then it is OK to replace.

**Comment by ziofat** [comment]
I am not sure `got` can support SSR or not. It might do if not using Stream related functions. I will try to make a PR and let you test with it.

**Comment by configcat** [comment]
Thanks for the PR. :)
It will take some time for us to test if it works well on all platforms.
