### ISSUE TITLE
JSONConfig is not present. Returning default value: 'false'.

### ISSUE THREAD

**Issue by tcdoorn** [configcat/node-sdk#9]
When running configcat in a NodeJS project we get the following console log error:
JSONConfig is not present. Returning default value: 'false'.

Occurs with all methods (getValue, getValueAsync. getAllKeys).
Tried upgrading (were on version 2.2.5, then tried 3.0.0, and also tried 2.4.0).
Do you have any idea what could cause this?
Thanks in advance.

**Comment by configcat** [comment]
Hi @tcdoorn !

Thanks for letting us know. We're looking into it right now.

**Comment by sigewuzhere** [comment]
I tried the Node.js Sample (https://github.com/configcat/node-sdk/tree/master/samples/console) on my local machine and it works. Can you try it so we can rule out local and network related issues?

**Comment by sigewuzhere** [comment]
Also it would be great if you could post here or send me in private the related code from your application.

**Comment by tcdoorn** [comment]
The sample is working on my machine. We're using configcat in a expressjs server side application from within a docker runtime. I've also tried running the project outside of Docker, but it's still not working. I've also added the sample to the startup of my project, but still the same issue occurs.
The same issue appears on my colleague's computer, so it doesn't seem to be a computer issue, but more of a dependency issue.
Which is weird, as i'm pretty sure it was working last week and we haven't changes dependencies since then.

**Comment by sigewuzhere** [comment]
This error is thrown here: https://github.com/configcat/common-js/blob/25c4fe8af58e63f31424cf06427c8c6a636a3665/src/RolloutEvaluator.ts#L47

Most likely it is thrown when the SDK did/could not download the config.json from our servers before you tried accessing the setting values. For example if you are using Manual Polling (https://configcat.com/docs/sdk-reference/node/#manual-polling) and did not call `forceRefresh()` before `getValue()`.

Which polling mode are you using?

I'll keep investigating it the meanwhile if there is a bug in the SDK.

**Comment by tcdoorn** [comment]
We're using the default polling method. The configcat client is initialized when the expressjs server is started. I've also tried adding the forceRefreshAsync call before calling the getValue, but the error keeps occuring. I've also run fiddler to see if a call to configcat was done. A call to cdn.configcat.com and api.configcat.com is done, but I can't however see the content as it's encrypted.

**Comment by tcdoorn** [comment]
Seems like it was a dependency issue on our side. There were some unused dependencies in our project, removed those. That also updated package-lock.json which probably solved the issue.

Thanks anyway for your help.

**Comment by sigewuzhere** [comment]
Oh good to hear, there was nothing else I could think of.
In the meanwhile we created a sample application matching your stack, might help debugging future issues: https://github.com/configcat/node-sdk/tree/master/samples/expresswithdocker
